### ISSUE TITLE
Running "orca source cflags" fails when cwd is on different drive than install folder

### ISSUE THREAD

**Issue by martinfouilleul** [orca-app/orca#9]
_Imported from gitea. See https://git.handmade.network/hmn/orca/issues/109 for previous conversation_

```
E:\Dev\handmade\test>orca source cflags
ERROR: Paths don't have the same drive
Traceback (most recent call last):
  File "C:\Users\Reuben\AppData\Local\orca\bin\sys_scripts\log.py", line 68, in shellfunc
    func(*args, **kwargs)
  File "C:\Users\Reuben\AppData\Local\orca\bin\sys_scripts\source.py", line 77, in cflags
    include = nicepath(args.srcdir)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Reuben\AppData\Local\orca\bin\sys_scripts\source.py", line 72, in nicepath
    if path_contains(os.getcwd(), path_abs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Reuben\AppData\Local\orca\bin\sys_scripts\source.py", line 68, in path_contains
    return os.path.commonpath([a_abs, b_abs]) == a_abs
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 814, in commonpath
ValueError: Paths don't have the same drive


Task failed with 1 error:
ERROR: Paths don't have the same drive
```

**Comment by martinfouilleul** [comment]
Closing because orca source has been retired.
